services:
  - type: web
    name: java-portfolio
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/java-portfolio-0.0.1-SNAPSHOT.jar
    plan: free
    healthCheckPath: /