spring.application.name=Varun Kishor Bhoi - Portfolio
server.port=8080
server.servlet.context-path=/
spring.mvc.static-path-pattern=/static/**
spring.resources.static-locations=classpath:/static/
spring.web.resources.static-locations=classpath:/static/

# Server configuration
server.servlet.session.timeout=30m

# Logging
logging.level.root=INFO
logging.level.com.example.java.portfolio=DEBUG
